version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_scripts/wkping-script.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: wkping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      IP_ADDRESS: ${IP_ADDRESS}

  spring-boot-app:
    image:  registry.gitlab.com/monitoring-app1/wkping-backend:latest
    container_name: wkping-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
